# Generated by Django 5.1.5 on 2025-02-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonyapp', '0002_order_retailer_delete_retailerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
