# Generated by Django 5.1.5 on 2025-02-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonyapp', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
