# Generated by Django 5.1.5 on 2025-02-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonyapp', '0006_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
