# Generated by Django 5.1.5 on 2025-02-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonyapp', '0009_remove_shipment_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='shipment_priority',
        ),
    ]
