# Generated by Django 5.1.5 on 2025-02-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonyapp', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
