# Generated by Django 5.1.5 on 2025-02-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonyapp', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='truck',
        ),
    ]
