# Generated by Django 5.1.5 on 2025-02-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonyapp', '0012_employee_user_retailer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='user',
        ),
    ]
