# Generated by Django 5.1.5 on 2025-02-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonyapp', '0013_remove_employee_user_remove_retailer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
